# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '001---直播架构搭建' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 001---直播架构搭建
  pod "AFNetworking", "~> 2.0"
  pod "AFDownloadRequestOperation", "~> 2.0.1"
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'MSWeakTimer', '~> 1.1.0'
  pod 'pop', '~> 1.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'TYAttributedLabel', '~> 2.6.9'
  


end
